name: backend

on:
  push:
    branches: [ "master" ]
    paths:
      - backend


defaults:
      run:
        working-directory: backend

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install and build
      run: |
        npm install
        npm run build
      env: 
        CI: true
        
  depoly:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
          script: |
            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
            . ~/.nvm/nvm.sh
            nvm instal 16
            npm install -g pm2
            cd /home/ubuntu
            sudo rm -rf health
            git clone https://github.com/asifjoardar/health.git
            cd /home/ubuntu/health/backend
            npm install
            npm run build
            pm2 start npm --name health-backend -- run prod
            pm2 restart health-backend
    
