name: backend

on:
  push:
    branches: [ "master" ]
    paths:
      - backend

  workflow_dispatch:

defaults:
      run:
        working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: npm install
        env: 
          CI: true   


  depoly:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
            . ~/.nvm/nvm.sh
            nvm instal 16
            npm install -g pm2
            cd ~/health
            git pull origin master
            cd /backend
            rm -rf node_modules package-lock.json
            npm install
            pm2 restart backend

