
name: deploy-backend

on:
  push:
    branches: [ "master" ]

defaults:
      run:
        working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build
        env: 
          CI: true   


  depoly:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          port:  ${{ secrets.PORT }}
          script: |
              curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
              . ~/.nvm/nvm.sh
               nvm instal 16
               npm install -g pm2
               cd ~/backend
               git pull origin master
               cd health/backend
               npm install
               npm run build
               pm2 restart backend
            
